name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: |
          rm -rf ./build

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./build/simple-blacklist-linux-amd64
          gzip -f -q ./build/simple-blacklist-linux-amd64

          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o ./build/simple-blacklist-linux-arm64
          gzip -f -q ./build/simple-blacklist-linux-arm64

          CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o ./build/simple-blacklist-linux-arm
          gzip -f -q ./build/simple-blacklist-linux-arm

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: test release
          draft: false
          prerelease: false

      - name: Upload simple-blacklist-linux-amd64 asset
        id: upload-simple-blacklist-linux-amd64-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/simple-blacklist-linux-amd64.gz
          asset_name: simple-blacklist-linux-amd64.gz
          asset_content_type: application/gzip

      - name: Upload simple-blacklist-linux-arm64 asset
        id: upload-simple-blacklist-linux-arm64-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/simple-blacklist-linux-arm64.gz
          asset_name: simple-blacklist-linux-arm64.gz
          asset_content_type: application/gzip

      - name: upload simple-blacklist-linux-arm asset
        id: upload-simple-blacklist-linux-arm-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/simple-blacklist-linux-arm.gz
          asset_name: simple-blacklist-linux-arm.gz
          asset_content_type: application/gzip
